use_frameworks!

target 'ROCController_Example' do
  pod 'ROCController', :path => '../'
  pod 'Fakery', '~> 2.0.0'
  pod 'Kingfisher', '~> 3.5.2'

  target 'ROCController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 6.0.1'
  pod 'FBSnapshotTestCase', '~> 2.1.4'
  pod 'Nimble-Snapshots', '~> 4.4.0'
  end
end
